import type { Metadata } from "next";
import { Navbar } from "@/components/landing/navbar";
import { Footer } from "@/components/landing/footer";
import { PageHeader } from "@/components/marketing/page-header";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of CareerVerse AI.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main>
        <PageHeader eyebrow="Legal" title="Terms of Service" />
        <section className="pb-24">
          <div className="container mx-auto max-w-2xl space-y-10 text-sm leading-relaxed text-muted">
            <p className="text-xs text-muted/70">Last updated: July 22, 2026</p>

            <div>
              <h2 className="mb-3 font-display text-lg font-semibold text-foreground">1. Acceptance of terms</h2>
              <p>
                By creating an account or using CareerVerse AI, you agree to these terms. If you
                don't agree, please don't use the platform.
              </p>
            </div>

            <div>
              <h2 className="mb-3 font-display text-lg font-semibold text-foreground">2. What CareerVerse AI is</h2>
              <p>
                CareerVerse AI provides career exploration tools, including a career quiz and
                simulated work scenarios, along with AI-generated feedback and compatibility
                scores. These outputs are informational and directional — they are not
                professional career counseling, guaranteed job outcomes, or a substitute for
                speaking with a licensed career counselor.
              </p>
            </div>

            <div>
              <h2 className="mb-3 font-display text-lg font-semibold text-foreground">3. Your account</h2>
              <p>
                You're responsible for keeping your account credentials secure and for all
                activity under your account. You must provide accurate information when signing
                up and be at least 13 years old to create an account.
              </p>
            </div>

            <div>
              <h2 className="mb-3 font-display text-lg font-semibold text-foreground">4. Subscriptions & billing</h2>
              <p>
                Plus and Teams plans are billed on a recurring basis until canceled. You can cancel
                anytime from your account settings; you'll retain access through the end of your
                current billing period. We don't offer retroactive refunds for partial billing
                periods except where required by law.
              </p>
            </div>

            <div>
              <h2 className="mb-3 font-display text-lg font-semibold text-foreground">5. Acceptable use</h2>
              <p>
                You agree not to misuse the platform — including attempting to access other users'
                data, reverse-engineering our simulation or scoring systems, or using the service
                to generate harmful, abusive, or illegal content.
              </p>
            </div>

            <div>
              <h2 className="mb-3 font-display text-lg font-semibold text-foreground">6. Certificates</h2>
              <p>
                Certificates generated by CareerVerse AI reflect performance within our simulation
                environment. They are not accredited qualifications and should be treated as a
                personal development artifact, not a professional credential.
              </p>
            </div>

            <div>
              <h2 className="mb-3 font-display text-lg font-semibold text-foreground">7. Termination</h2>
              <p>
                We may suspend or terminate accounts that violate these terms. You may delete your
                account at any time from your dashboard settings.
              </p>
            </div>

            <div>
              <h2 className="mb-3 font-display text-lg font-semibold text-foreground">8. Limitation of liability</h2>
              <p>
                CareerVerse AI is provided "as is." We work to keep career data and simulations
                accurate but don't guarantee completeness or that following our recommendations
                will lead to any particular career outcome.
              </p>
            </div>

            <div>
              <h2 className="mb-3 font-display text-lg font-semibold text-foreground">9. Changes to these terms</h2>
              <p>
                We may update these terms as the product evolves. Continued use after an update
                constitutes acceptance of the revised terms.
              </p>
            </div>

            <div>
              <h2 className="mb-3 font-display text-lg font-semibold text-foreground">10. Contact</h2>
              <p>
                Questions about these terms? Email{" "}
                <a href="mailto:legal@careerverse.ai" className="text-primary-400 hover:underline">
                  legal@careerverse.ai
                </a>
                .
              </p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
